language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install pipenv
  - pipenv install

script:
  - pycodestyle --ignore=E501 cicero.py
  - pycodestyle --ignore=E501 cicero
  - pipenv run py.test -vv -s cicero/*

notifications:
  email: false
